<a href="https://colab.research.google.com/github/Bharatgwl/Pytorch-/blob/main/Dataloader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from sklearn.datasets import make_classification
import torch


In [6]:
X,y = make_classification(n_samples=100 , n_features = 2, n_informative=2, n_redundant=0,n_classes=2, random_state=42)

In [7]:
X

array([[ 0.55942643,  2.38869353],
       [ 1.31217492, -0.7173148 ],
       [-1.5598485 , -1.92487377],
       [-2.2813861 , -0.1368559 ],
       [ 1.56070438, -0.42795824],
       [-0.80804463,  1.19664076],
       [-0.27062383, -2.25553963],
       [ 0.480502  ,  0.54914434],
       [-1.20757158, -1.26898369],
       [ 0.25415746, -1.79532002],
       [ 2.59123946,  0.24472415],
       [ 0.07123641,  0.49429823],
       [-1.17762637, -1.20592943],
       [ 0.93343952,  0.68811892],
       [ 1.65214494, -0.35885569],
       [-1.40735658, -1.56826626],
       [ 1.02255619, -1.08324727],
       [-0.81680628, -0.6795874 ],
       [ 1.50575249, -0.38919817],
       [-2.17105282, -0.04862909],
       [ 0.71479373, -1.42922002],
       [-0.15013844, -0.11708689],
       [-1.4117586 , -1.5332749 ],
       [-2.58590856, -0.40925706],
       [ 0.82600732, -1.05383855],
       [-0.07133524,  0.08896214],
       [ 0.6273745 , -1.32933233],
       [ 1.65882246, -0.43131517],
       [ 1.2798899 ,

In [8]:
y

array([0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0])

In [9]:
X.shape

(100, 2)

In [10]:
y.shape

(100,)

In [11]:
X = torch.tensor(X,dtype=torch.float32)
y = torch.tensor(y,dtype=torch.long)

In [12]:
from torch.utils.data import Dataset, DataLoader


In [19]:
class customdataset(Dataset):
  def __init__(self, features , labels):
    self.features = features
    self.labels = labels
  def __len__(self):
    return self.features.shape[0]
  def __getitem__(self, index):
    return self.features[index], self.labels[index]


In [20]:
dataset = customdataset(X,y)

In [21]:
len(dataset)

100

In [26]:
dataset[1]

(tensor([ 1.3122, -0.7173]), tensor(1))

In [27]:
dataloader = DataLoader(dataset, batch_size=10, shuffle=True)

In [29]:
for feature,label in dataloader:
  print(feature)
  print(label)
  print("-"*50)

tensor([[ 1.0989,  1.2529],
        [ 0.4506, -1.5008],
        [ 1.0226, -1.0832],
        [ 1.0866, -1.0054],
        [-1.5598, -1.9249],
        [ 0.2506,  0.1398],
        [-0.3314,  1.5693],
        [-0.0532,  1.8561],
        [ 1.5723,  1.4992],
        [ 0.9642,  0.5560]])
tensor([1, 1, 1, 1, 0, 1, 0, 0, 1, 1])
--------------------------------------------------
tensor([[-2.3280, -0.1759],
        [-0.3490,  1.5601],
        [-1.1321,  0.8908],
        [-1.0322,  0.9480],
        [ 0.1551,  1.9981],
        [-1.0983, -0.8602],
        [ 1.2801,  1.2894],
        [ 0.9334,  0.6881],
        [ 0.6653,  0.8863],
        [-1.1776, -1.2059]])
tensor([0, 0, 0, 0, 0, 0, 1, 1, 1, 0])
--------------------------------------------------
tensor([[-0.8168, -0.6796],
        [ 1.0827, -0.9802],
        [-1.1581,  0.8656],
        [-0.2706, -2.2555],
        [-0.5750, -0.3751],
        [ 0.3413,  0.5730],
        [-2.0583, -2.5234],
        [ 1.8399,  2.3045],
        [ 1.3122, -0.7173],
      

# Full Pytorch training pipeline


In [30]:
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import torch.nn as nn
from torch.utils.data import Dataset ,DataLoader

In [31]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [32]:
df.drop(columns=['Unnamed: 32','id'],inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [33]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['diagnosis']),df['diagnosis'],test_size=0.2,random_state=42   )

In [34]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [35]:
X_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [37]:
X_test

array([[-0.46649743, -0.13728933, -0.44421138, ..., -0.19435087,
         0.17275669,  0.20372995],
       [ 1.36536344,  0.49866473,  1.30551088, ...,  0.99177862,
        -0.561211  , -1.00838949],
       [ 0.38006578,  0.06921974,  0.40410139, ...,  0.57035018,
        -0.10783139, -0.20629287],
       ...,
       [-0.73547237, -0.99852603, -0.74138839, ..., -0.27741059,
        -0.3820785 , -0.32408328],
       [ 0.02898271,  2.0334026 ,  0.0274851 , ..., -0.49027026,
        -1.60905688, -0.33137507],
       [ 1.87216885,  2.80077153,  1.80354992, ...,  0.7925579 ,
        -0.05868885, -0.09467243]])

In [42]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [44]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))


In [45]:
X_train_tensor.shape

torch.Size([455, 30])

In [46]:
X_test_tensor.shape

torch.Size([114, 30])

In [53]:
class customdataset(Dataset):
  def __init__(self, features, output_labels):
    self.features = features
    self.output_labels = output_labels
  def __len__(self):
    return self.features.shape[0]
  def __getitem__(self, index):
    return self.features[index], self.output_labels[index]

In [54]:
train_dataset = customdataset(X_train_tensor,y_train_tensor)
test_dataset = customdataset(X_test_tensor,y_test_tensor)

In [55]:
train_dataset[10]

(tensor([-0.4976,  0.6137, -0.4981, -0.5310, -0.5769, -0.1749, -0.3622, -0.2849,
          0.4335,  0.1782, -0.3684,  0.5531, -0.3167, -0.4052,  0.0403, -0.0380,
         -0.1804,  0.1648, -0.1217,  0.2308, -0.5004,  0.8194, -0.4692, -0.5331,
         -0.0491, -0.0416, -0.1491,  0.0968,  0.1062,  0.4904]),
 tensor(0.))

In [56]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32,shuffle=True)

In [67]:
class NNN(nn.Module):
  def __init__(self, input_features):
    super().__init__()
    self.linear = nn.Linear(input_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    out = self.linear(x)
    out = self.sigmoid(out)
    return out

In [68]:
epoch = 30
lr = 0.1
loss_function = nn.BCELoss()
model = NNN(X_train_tensor.shape[1])
optim = torch.optim.SGD(model.parameters(), lr = lr)

In [73]:
def train():
  for e in range(epoch):
    for batch_features , batch_labels in train_loader:
      y_pred  = model(batch_features) # forward pass
      loss = loss_function(y_pred, batch_labels.view(-1,1).float()) # loss calc
      optim.zero_grad() # clear old grad
      loss.backward()# backward pass
      optim.step() # update params
    print(f"epoch:{e+1} , loss:{loss.item()}")



In [74]:
train()

epoch:1 , loss:0.2034185826778412
epoch:2 , loss:0.28607824444770813
epoch:3 , loss:0.09523718804121017
epoch:4 , loss:0.10476838797330856
epoch:5 , loss:0.5867264866828918
epoch:6 , loss:0.2405385971069336
epoch:7 , loss:0.09508959203958511
epoch:8 , loss:0.22394077479839325
epoch:9 , loss:0.12591852247714996
epoch:10 , loss:0.01165680680423975
epoch:11 , loss:0.11644840240478516
epoch:12 , loss:0.2860313951969147
epoch:13 , loss:0.02773565985262394
epoch:14 , loss:0.33314114809036255
epoch:15 , loss:0.05264398828148842
epoch:16 , loss:0.1155465766787529
epoch:17 , loss:0.010151242837309837
epoch:18 , loss:0.02656741440296173
epoch:19 , loss:0.04663631319999695
epoch:20 , loss:0.061922457069158554
epoch:21 , loss:0.06043693795800209
epoch:22 , loss:0.016149049624800682
epoch:23 , loss:0.14089281857013702
epoch:24 , loss:0.03618628531694412
epoch:25 , loss:0.4615618586540222
epoch:26 , loss:0.01000453531742096
epoch:27 , loss:0.010996143333613873
epoch:28 , loss:0.05652202293276787
epo