<a href="https://colab.research.google.com/github/Bharatgwl/Pytorch-/blob/main/PytorchNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
import torch
import torch.nn as nn


In [64]:
class model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
    def forward(self,x): ## forward name is important as it is used by the model when we call the model on some data
        return self.sigmoid(self.linear(x))



In [65]:
features = torch.randn((10,5))

In [66]:
features.shape[1]

5

In [67]:
model = model(features.shape[1])

In [68]:
model(features) ### this is how we call the model on some data, it will automatically call the forward method of the model and pass the data to it.

tensor([[0.5040],
        [0.4070],
        [0.4766],
        [0.5791],
        [0.5947],
        [0.6269],
        [0.2445],
        [0.3857],
        [0.4786],
        [0.6620]], grad_fn=<SigmoidBackward0>)

In [69]:
# O

# O   O

# O   O   O -- y_pred

# O   O

# O

In [70]:
class model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features,3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()
    def forward(self,x): ## forward name is important as it is used by the model when we call the model on some data
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out



In [71]:
model = model(num_features=5)
model(features)


tensor([[0.5072],
        [0.4205],
        [0.3551],
        [0.3871],
        [0.4532],
        [0.5109],
        [0.4070],
        [0.4413],
        [0.5067],
        [0.5053]], grad_fn=<SigmoidBackward0>)

In [72]:
model.linear1.weight

Parameter containing:
tensor([[ 0.4194,  0.3720, -0.4391,  0.3878,  0.0896],
        [-0.1025, -0.4295, -0.2673, -0.4458,  0.3349],
        [ 0.0133,  0.3797, -0.0320,  0.0270,  0.0327]], requires_grad=True)

In [73]:
!pip install torchinfo

In [74]:
from torchinfo import summary

In [75]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [76]:
import numpy as np
import pandas as pd
import torch
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import torch.nn as nn

In [77]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [78]:
df.drop(columns=['Unnamed: 32','id'],inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [79]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['diagnosis']),df['diagnosis'],test_size=0.2,random_state=42)

In [80]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [81]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [82]:
X_train_tensor = torch.FloatTensor(X_train)
X_test_tensor = torch.FloatTensor(X_test)
y_train_tensor = torch.LongTensor(y_train)
y_test_tensor = torch.LongTensor(y_test)

In [83]:
class MysimpleNN(nn.Module):
  def __init__(self,input_features):
    super().__init__()
    self.linear1 = nn.Linear(input_features,1)
    self.sigmoid = nn.Sigmoid()
  def forward(self,x):
    out = self.linear1(x)
    out = self.sigmoid(out)
    return out
  def loss(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    loss = -(y * torch.log(y_pred) +
             (1 - y) * torch.log(1 - y_pred)).mean()

    return loss

In [84]:
lr= 0.1
epochs = 25



In [85]:
model = MysimpleNN(X_train_tensor.shape[1])

In [86]:
for epoch in range(epochs):

  ypred = model.forward(X_train_tensor)
  loss = model.loss(ypred,y_train_tensor)

  loss.backward()

  with torch.no_grad():
    model.linear1.weight-=lr*model.linear1.weight.grad
    model.linear1.bias-=lr*model.linear1.bias.grad

  model.linear1.weight.grad.zero_()
  model.linear1.bias.grad.zero_()

  print(f"epochs : {epoch+1} loss : {loss}")


epochs : 1 loss : 0.7345793843269348
epochs : 2 loss : 0.7222360968589783
epochs : 3 loss : 0.7135369181632996
epochs : 4 loss : 0.7071276307106018
epochs : 5 loss : 0.7021898627281189
epochs : 6 loss : 0.6982331275939941
epochs : 7 loss : 0.6949596405029297
epochs : 8 loss : 0.6921828389167786
epochs : 9 loss : 0.6897814869880676
epochs : 10 loss : 0.687673032283783
epochs : 11 loss : 0.685799241065979
epochs : 12 loss : 0.6841174960136414
epochs : 13 loss : 0.6825959086418152
epochs : 14 loss : 0.6812097430229187
epochs : 15 loss : 0.6799401640892029
epochs : 16 loss : 0.6787714958190918
epochs : 17 loss : 0.6776919364929199
epochs : 18 loss : 0.6766911745071411
epochs : 19 loss : 0.6757609844207764
epochs : 20 loss : 0.6748943328857422
epochs : 21 loss : 0.6740854978561401
epochs : 22 loss : 0.6733291745185852
epochs : 23 loss : 0.6726210117340088
epochs : 24 loss : 0.6719571352005005
epochs : 25 loss : 0.6713340282440186


In [87]:
ypred = model.forward(X_train_tensor)

In [88]:
model.loss(ypred,y_train_tensor)

tensor(0.6707, grad_fn=<NegBackward0>)

In [89]:
with torch.no_grad():
  ypred = model.forward(X_test_tensor)
  ypred = (ypred>0.9).float()
  accuracy = (ypred == y_test_tensor).float().mean()
  print(f"accuracy : {accuracy}")


accuracy : 0.6228070259094238


# New Section
**now using loss and optim in torch**

In [90]:
class MysimpleNN(nn.Module):
  def __init__(self,input_features):
    super().__init__()
    self.linear1 = nn.Linear(input_features,1)
    self.sigmoid = nn.Sigmoid()
  def forward(self,x):
    out = self.linear1(x)
    out = self.sigmoid(out)
    return out


In [91]:
lr= 0.1
epochs = 25

loss_function = nn.BCELoss()


In [92]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [93]:
model = MysimpleNN(X_train_tensor.shape[1])
optimiser = torch.optim.SGD(model.parameters(),lr=lr)

In [94]:
for epoch in range(epochs):
  # forward pass
  ypred = model(X_train_tensor)
  # loss calc
  loss = loss_function(ypred, y_train_tensor.reshape(-1,1).float())
  # clear old grads
  optimiser.zero_grad()
  # backprop
  loss.backward()
  # param update
  optimiser.step()

  print(f"epochs : {epoch+1} loss : {loss}")

epochs : 1 loss : 0.4777575433254242
epochs : 2 loss : 0.4028390347957611
epochs : 3 loss : 0.35642358660697937
epochs : 4 loss : 0.32453230023384094
epochs : 5 loss : 0.30101028084754944
epochs : 6 loss : 0.28277018666267395
epochs : 7 loss : 0.2680932283401489
epochs : 8 loss : 0.2559444308280945
epochs : 9 loss : 0.24566210806369781
epochs : 10 loss : 0.23680253326892853
epochs : 11 loss : 0.2290564924478531
epochs : 12 loss : 0.22220160067081451
epochs : 13 loss : 0.21607333421707153
epochs : 14 loss : 0.21054723858833313
epochs : 15 loss : 0.20552721619606018
epochs : 16 loss : 0.2009376883506775
epochs : 17 loss : 0.19671840965747833
epochs : 18 loss : 0.19282041490077972
epochs : 19 loss : 0.18920378386974335
epochs : 20 loss : 0.18583519756793976
epochs : 21 loss : 0.182686910033226
epochs : 22 loss : 0.17973533272743225
epochs : 23 loss : 0.17696043848991394
epochs : 24 loss : 0.1743449568748474
epochs : 25 loss : 0.17187398672103882


In [95]:
with torch.no_grad():
  ypred = model.forward(X_test_tensor)
  ypred = (ypred>0.9).float()
  accuracy = (ypred == y_test_tensor).float().mean()
  print(f"accuracy : {accuracy}")

accuracy : 0.5646352767944336
