<a href="https://colab.research.google.com/github/Bharatgwl/Pytorch-/blob/main/Pytorch_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [ ]:
df.drop(columns=['Unnamed: 32','id'],inplace=True)
df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['diagnosis']),df['diagnosis'],test_size=0.2,random_state=42)

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [ ]:
y_train

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: object

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train
y_test


array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1])

In [ ]:
X_train_tensor = torch.FloatTensor(X_train)
X_test_tensor = torch.FloatTensor(X_test)
y_train_tensor = torch.LongTensor(y_train)
y_test_tensor = torch.LongTensor(y_test)

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

**Define the model**

In [ ]:
class MysimpleNN():
  def __init__(self, X):
    self.weights = torch.randn(X.shape[1],dtype=torch.float32,requires_grad=True)
    self.bias = torch.zeros(1,dtype=torch.float32,requires_grad=True)
  def forward(self, X):
    z = torch.matmul(X,self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred
  def loss(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    loss = -(y * torch.log(y_pred) +
             (1 - y) * torch.log(1 - y_pred)).mean()
    return loss


In [ ]:
learning_rate = 0.1
epochs = 25


In [ ]:
# create model
model = MysimpleNN(X_train_tensor)
model.weights

tensor([ 0.0313, -0.6701,  0.4247, -0.0128,  0.9875, -1.4067, -0.7845,  0.3662,
         0.0096,  0.8411,  0.4769,  0.1943, -0.8395, -0.0620,  1.5868,  0.1256,
         0.0511, -0.1934, -1.2636,  0.5511, -0.5481, -0.1238, -0.4007,  0.5890,
         0.5145,  0.2941, -1.9159, -1.5635,  1.4229, -0.4217],
       requires_grad=True)

In [ ]:
model.bias

tensor([0.], requires_grad=True)

In [ ]:
for i in range(epochs):
  y_pred = model.forward(X_train_tensor)

  loss = model.loss(y_pred,y_train_tensor)

  loss.backward()
  with torch.no_grad():
    model.weights -= learning_rate*model.weights.grad
    model.bias -= learning_rate*model.bias.grad

    model.weights.grad.zero_()
    model.bias.grad.zero_()

  # print loss in each
  print(f'Epoch {i+1} loss: {loss.item()}')

Epoch 1 loss: 3.3331775665283203
Epoch 2 loss: 2.728956937789917
Epoch 3 loss: 2.205502510070801
Epoch 4 loss: 1.7700685262680054
Epoch 5 loss: 1.4306086301803589
Epoch 6 loss: 1.1868712902069092
Epoch 7 loss: 1.012192964553833
Epoch 8 loss: 0.8828393816947937
Epoch 9 loss: 0.7835676074028015
Epoch 10 loss: 0.7050057649612427
Epoch 11 loss: 0.6412683725357056
Epoch 12 loss: 0.5885174870491028
Epoch 13 loss: 0.5441204905509949
Epoch 14 loss: 0.5062407851219177
Epoch 15 loss: 0.4735415279865265
Epoch 16 loss: 0.4450337290763855
Epoch 17 loss: 0.41996756196022034
Epoch 18 loss: 0.3977692127227783
Epoch 19 loss: 0.3779868185520172
Epoch 20 loss: 0.3602583706378937
Epoch 21 loss: 0.3442905843257904
Epoch 22 loss: 0.32984089851379395
Epoch 23 loss: 0.3167073726654053
Epoch 24 loss: 0.30472037196159363
Epoch 25 loss: 0.2937372326850891


In [ ]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()