In [1]:
import pandas as pd 


In [2]:
df = pd.read_csv("Data/100_Unique_QA_Dataset.csv")

In [3]:
df.head()

,question,answer
0,What is the capital of France?,Paris
1,What is the capital of Germany?,Berlin
2,Who wrote 'To Kill a Mockingbird'?,Harper-Lee
3,What is the largest planet in our solar system?,Jupiter
4,What is the boiling point of water in Celsius?,100


In [4]:
# tokenize
def tokenize(text):
    text = text.lower()
    text = text.replace("?","")
    text = text.replace("'","")
    return text.split()

In [6]:
tokenize(df["question"][0])

['what', 'is', 'the', 'capital', 'of', 'france']

In [7]:
# vocab 

vocab = {'<UNK>':0}


In [21]:
def build_vocab(texts):
    tokenized_question = tokenize(texts['question'])
    tokenized_ans = tokenize(texts['answer'])
    
    merged = tokenized_question + tokenized_ans
    print(merged)
    
    for word in merged:
        if word not in vocab:
            vocab[word] = len(vocab)

In [22]:
df.apply(build_vocab, axis=1)

['what', 'is', 'the', 'capital', 'of', 'france', 'paris']
['what', 'is', 'the', 'capital', 'of', 'germany', 'berlin']
['who', 'wrote', 'to', 'kill', 'a', 'mockingbird', 'harper-lee']
['what', 'is', 'the', 'largest', 'planet', 'in', 'our', 'solar', 'system', 'jupiter']
['what', 'is', 'the', 'boiling', 'point', 'of', 'water', 'in', 'celsius', '100']
['who', 'painted', 'the', 'mona', 'lisa', 'leonardo-da-vinci']
['what', 'is', 'the', 'square', 'root', 'of', '64', '8']
['what', 'is', 'the', 'chemical', 'symbol', 'for', 'gold', 'au']
['which', 'year', 'did', 'world', 'war', 'ii', 'end', '1945']
['what', 'is', 'the', 'longest', 'river', 'in', 'the', 'world', 'nile']
['what', 'is', 'the', 'capital', 'of', 'japan', 'tokyo']
['who', 'developed', 'the', 'theory', 'of', 'relativity', 'albert-einstein']
['what', 'is', 'the', 'freezing', 'point', 'of', 'water', 'in', 'fahrenheit', '32']
['which', 'planet', 'is', 'known', 'as', 'the', 'red', 'planet', 'mars']
['who', 'is', 'the', 'author', 'of', '19

0     None
1     None
2     None
3     None
4     None
      ... 
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [23]:
vocab

{'<UNK>': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'who': 10,
 'wrote': 11,
 'to': 12,
 'kill': 13,
 'a': 14,
 'mockingbird': 15,
 'harper-lee': 16,
 'largest': 17,
 'planet': 18,
 'in': 19,
 'our': 20,
 'solar': 21,
 'system': 22,
 'jupiter': 23,
 'boiling': 24,
 'point': 25,
 'water': 26,
 'celsius': 27,
 '100': 28,
 'painted': 29,
 'mona': 30,
 'lisa': 31,
 'leonardo-da-vinci': 32,
 'square': 33,
 'root': 34,
 '64': 35,
 '8': 36,
 'chemical': 37,
 'symbol': 38,
 'for': 39,
 'gold': 40,
 'au': 41,
 'which': 42,
 'year': 43,
 'did': 44,
 'world': 45,
 'war': 46,
 'ii': 47,
 'end': 48,
 '1945': 49,
 'longest': 50,
 'river': 51,
 'nile': 52,
 'japan': 53,
 'tokyo': 54,
 'developed': 55,
 'theory': 56,
 'relativity': 57,
 'albert-einstein': 58,
 'freezing': 59,
 'fahrenheit': 60,
 '32': 61,
 'known': 62,
 'as': 63,
 'red': 64,
 'mars': 65,
 'author': 66,
 '1984': 67,
 'george-orwell': 68,
 'currency': 69,
 'unit

In [26]:
# convert to index
def text_to_index(text,vocab):
    indexe_text = []
    
    for word in tokenize(text):
        
        if word in vocab:
            indexe_text.append(vocab[word])
        else:
            indexe_text.append(vocab['<UNK>'])
            
    return indexe_text
    

In [29]:
text = "What is the capital of cam?"
text_to_index(text,vocab)

[1, 2, 3, 4, 5, 0]

In [30]:
import torch 
from torch.utils.data import Dataset, DataLoader

In [31]:
class QADataset(Dataset):
    def __init__(self, df, vocab):
        self.df = df
        self.vocab = vocab
        
    def __len__(self):
        return len(self.df)
    
    def __getitem__(self, idx):
        question = self.df.iloc[idx]['question']
        answer = self.df.iloc[idx]['answer']
        
        question_indexed = text_to_index(question,self.vocab)
        answer_indexed = text_to_index(answer,self.vocab)
        
        return torch.tensor(question_indexed),torch.tensor(answer_indexed)
        

In [32]:
dataset = QADataset(df,vocab)

In [33]:
dataset[0]

(tensor([1, 2, 3, 4, 5, 6]), tensor([7]))

In [34]:
dataloader = DataLoader(dataset, batch_size=1, shuffle=True)


In [37]:
for question, answer in dataloader:
    print(question, answer)
    
    

tensor([[  1,  87, 229, 230, 231, 232]]) tensor([[233]])
tensor([[ 10, 140,   3, 141, 171,   5,   3,  70, 172]]) tensor([[173]])
tensor([[ 10,  11, 189, 158, 190]]) tensor([[191]])
tensor([[ 42,  18, 118,   3, 186, 187]]) tensor([[188]])
tensor([[ 10,  29, 130, 131]]) tensor([[132]])
tensor([[ 1,  2,  3, 37, 38, 39, 40]]) tensor([[41]])
tensor([[10, 55,  3, 56,  5, 57]]) tensor([[58]])
tensor([[42, 18,  2, 62, 63,  3, 64, 18]]) tensor([[65]])
tensor([[10, 11, 12, 13, 14, 15]]) tensor([[16]])
tensor([[  1,   2,   3, 122, 123,  19,   3,  45]]) tensor([[124]])
tensor([[ 78,  79, 195,  81,  19,   3, 196, 197, 198]]) tensor([[199]])
tensor([[  1,   2,   3,   4,   5, 113]]) tensor([[114]])
tensor([[  1,   2,   3, 141, 117,  83,   3, 277, 278]]) tensor([[121]])
tensor([[1, 2, 3, 4, 5, 8]]) tensor([[9]])
tensor([[ 10,  75, 208]]) tensor([[209]])
tensor([[ 42, 263, 264,  14, 265, 266, 158, 267]]) tensor([[268]])
tensor([[ 10, 308,   3, 309, 310]]) tensor([[311]])
tensor([[ 1,  2,  3, 50, 51, 19

In [40]:
class MysimpleRNN(torch.nn.Module):
    def __init__(self, vocab_size):
        super(MysimpleRNN, self).__init__()
        self.vocab_size = vocab_size
        self.embedding = torch.nn.Embedding(vocab_size, embedding_dim=50)
        self.rnn = torch.nn.RNN(input_size = 50 , hidden_size = 50, batch_first = True) 
        self.fc = torch.nn.Linear(50, vocab_size)
    def forward(self, x):
        x = self.embedding(x)
        hidden, final = self.rnn(x)
        output = self.fc(final.squeeze(0))
        return output

In [59]:
learning_rate = 0.001
epochs = 30 
criterion = torch.nn.CrossEntropyLoss()
model = MysimpleRNN(len(vocab)).to(torch.device("cuda"))
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [60]:
for epoch in range(epochs):
    total_loss = 0
    for question ,answer in dataloader:
        question = question.to(torch.device("cuda"))
        answer = answer.to(torch.device("cuda"))
        
        output = model(question)
        loss = criterion(output, answer.squeeze(1))
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")

Epoch 1, Loss: 527.8207
Epoch 2, Loss: 471.5562
Epoch 3, Loss: 407.2579
Epoch 4, Loss: 348.9800
Epoch 5, Loss: 303.0639
Epoch 6, Loss: 261.2390
Epoch 7, Loss: 222.9422
Epoch 8, Loss: 187.3279
Epoch 9, Loss: 155.4670
Epoch 10, Loss: 127.6535
Epoch 11, Loss: 104.0402
Epoch 12, Loss: 84.7566
Epoch 13, Loss: 69.7343
Epoch 14, Loss: 56.9960
Epoch 15, Loss: 47.3071
Epoch 16, Loss: 39.5818
Epoch 17, Loss: 33.4921
Epoch 18, Loss: 28.8148
Epoch 19, Loss: 24.7582
Epoch 20, Loss: 21.6338
Epoch 21, Loss: 18.6381
Epoch 22, Loss: 16.7763
Epoch 23, Loss: 14.8439
Epoch 24, Loss: 13.2334
Epoch 25, Loss: 11.8133
Epoch 26, Loss: 10.5318
Epoch 27, Loss: 9.4969
Epoch 28, Loss: 8.5691
Epoch 29, Loss: 7.7636
Epoch 30, Loss: 7.0637


In [61]:
def pred(model, question, vocab):
    model.eval()
    with torch.no_grad():
        question_indexed = text_to_index(question, vocab)
        question_tensor = torch.tensor(question_indexed).unsqueeze(0).to(torch.device("cuda")) # unsqueeze to add batch dimension
        output = model(question_tensor)
        probs = torch.nn.functional.softmax(output, dim=1)
        
        values, index = torch.max(probs, dim=1)
        
        if values.item() < 0.5:  # Threshold for confidence
            return "I don't know the answer to that question."
        else:
            for word, idx in vocab.items():
                if idx == index.item():
                    return word


In [70]:
pred(model, "What is the largest planet in our solar system", vocab)

'jupiter'